#ifndef STANDALONE_RENDERER_STUBS_COMPONENTS_VIZ_COMMON_BUILDFLAGS_H_
#define STANDALONE_RENDERER_STUBS_COMPONENTS_VIZ_COMMON_BUILDFLAGS_H_

#include "build/buildflag.h"

#define BUILDFLAG_INTERNAL_ENABLE_CAST_OVERLAY_STRATEGY() (0)

#endif  // STANDALONE_RENDERER_STUBS_COMPONENTS_VIZ_COMMON_BUILDFLAGS_H_
