// Copyright 2026 The standalone renderer authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef STANDALONE_RENDERER_SRC_PRIVATE_VMA_SYMBOL_PREFIX_H_
#define STANDALONE_RENDERER_SRC_PRIVATE_VMA_SYMBOL_PREFIX_H_

// The static C API package links Blink/Skia's bundled Vulkan Memory Allocator
// into host binaries that may already own another VMA copy. Keep the C symbols
// private to this renderer by remapping VMA's public API names before including
// vk_mem_alloc.h in standalone-compiled VMA implementation/users.
#define vmaAllocateMemory blink_standalone_vmaAllocateMemory
#define vmaAllocateMemoryForBuffer blink_standalone_vmaAllocateMemoryForBuffer
#define vmaAllocateMemoryForImage blink_standalone_vmaAllocateMemoryForImage
#define vmaAllocateMemoryPages blink_standalone_vmaAllocateMemoryPages
#define vmaBeginDefragmentation blink_standalone_vmaBeginDefragmentation
#define vmaBeginDefragmentationPass blink_standalone_vmaBeginDefragmentationPass
#define vmaBindBufferMemory blink_standalone_vmaBindBufferMemory
#define vmaBindBufferMemory2 blink_standalone_vmaBindBufferMemory2
#define vmaBindImageMemory blink_standalone_vmaBindImageMemory
#define vmaBindImageMemory2 blink_standalone_vmaBindImageMemory2
#define vmaBuildStatsString blink_standalone_vmaBuildStatsString
#define vmaBuildVirtualBlockStatsString \
  blink_standalone_vmaBuildVirtualBlockStatsString
#define vmaCalculatePoolStatistics blink_standalone_vmaCalculatePoolStatistics
#define vmaCalculateStatistics blink_standalone_vmaCalculateStatistics
#define vmaCalculateVirtualBlockStatistics \
  blink_standalone_vmaCalculateVirtualBlockStatistics
#define vmaCheckCorruption blink_standalone_vmaCheckCorruption
#define vmaCheckPoolCorruption blink_standalone_vmaCheckPoolCorruption
#define vmaClearVirtualBlock blink_standalone_vmaClearVirtualBlock
#define vmaCreateAliasingBuffer blink_standalone_vmaCreateAliasingBuffer
#define vmaCreateAliasingBuffer2 blink_standalone_vmaCreateAliasingBuffer2
#define vmaCreateAliasingImage blink_standalone_vmaCreateAliasingImage
#define vmaCreateAliasingImage2 blink_standalone_vmaCreateAliasingImage2
#define vmaCreateAllocator blink_standalone_vmaCreateAllocator
#define vmaCreateBuffer blink_standalone_vmaCreateBuffer
#define vmaCreateBufferWithAlignment \
  blink_standalone_vmaCreateBufferWithAlignment
#define vmaCreateImage blink_standalone_vmaCreateImage
#define vmaCreatePool blink_standalone_vmaCreatePool
#define vmaCreateVirtualBlock blink_standalone_vmaCreateVirtualBlock
#define vmaDestroyAllocator blink_standalone_vmaDestroyAllocator
#define vmaDestroyBuffer blink_standalone_vmaDestroyBuffer
#define vmaDestroyImage blink_standalone_vmaDestroyImage
#define vmaDestroyPool blink_standalone_vmaDestroyPool
#define vmaDestroyVirtualBlock blink_standalone_vmaDestroyVirtualBlock
#define vmaEndDefragmentation blink_standalone_vmaEndDefragmentation
#define vmaEndDefragmentationPass blink_standalone_vmaEndDefragmentationPass
#define vmaFindMemoryTypeIndex blink_standalone_vmaFindMemoryTypeIndex
#define vmaFindMemoryTypeIndexForBufferInfo \
  blink_standalone_vmaFindMemoryTypeIndexForBufferInfo
#define vmaFindMemoryTypeIndexForImageInfo \
  blink_standalone_vmaFindMemoryTypeIndexForImageInfo
#define vmaFlushAllocation blink_standalone_vmaFlushAllocation
#define vmaFlushAllocations blink_standalone_vmaFlushAllocations
#define vmaFreeMemory blink_standalone_vmaFreeMemory
#define vmaFreeMemoryPages blink_standalone_vmaFreeMemoryPages
#define vmaFreeStatsString blink_standalone_vmaFreeStatsString
#define vmaFreeVirtualBlockStatsString \
  blink_standalone_vmaFreeVirtualBlockStatsString
#define vmaGetAllocationInfo blink_standalone_vmaGetAllocationInfo
#define vmaGetAllocationMemoryProperties \
  blink_standalone_vmaGetAllocationMemoryProperties
#define vmaGetAllocatorInfo blink_standalone_vmaGetAllocatorInfo
#define vmaGetHeapBudgets blink_standalone_vmaGetHeapBudgets
#define vmaGetMemoryProperties blink_standalone_vmaGetMemoryProperties
#define vmaGetMemoryTypeProperties blink_standalone_vmaGetMemoryTypeProperties
#define vmaGetPhysicalDeviceProperties \
  blink_standalone_vmaGetPhysicalDeviceProperties
#define vmaGetPoolName blink_standalone_vmaGetPoolName
#define vmaGetPoolStatistics blink_standalone_vmaGetPoolStatistics
#define vmaGetVirtualAllocationInfo blink_standalone_vmaGetVirtualAllocationInfo
#define vmaGetVirtualBlockStatistics \
  blink_standalone_vmaGetVirtualBlockStatistics
#define vmaInvalidateAllocation blink_standalone_vmaInvalidateAllocation
#define vmaInvalidateAllocations blink_standalone_vmaInvalidateAllocations
#define vmaIsVirtualBlockEmpty blink_standalone_vmaIsVirtualBlockEmpty
#define vmaMapMemory blink_standalone_vmaMapMemory
#define vmaSetAllocationName blink_standalone_vmaSetAllocationName
#define vmaSetAllocationUserData blink_standalone_vmaSetAllocationUserData
#define vmaSetCurrentFrameIndex blink_standalone_vmaSetCurrentFrameIndex
#define vmaSetPoolName blink_standalone_vmaSetPoolName
#define vmaSetVirtualAllocationUserData \
  blink_standalone_vmaSetVirtualAllocationUserData
#define vmaUnmapMemory blink_standalone_vmaUnmapMemory
#define vmaVirtualAllocate blink_standalone_vmaVirtualAllocate
#define vmaVirtualFree blink_standalone_vmaVirtualFree

#endif  // STANDALONE_RENDERER_SRC_PRIVATE_VMA_SYMBOL_PREFIX_H_
