// Generated by standalone CMake for BLINK_STANDALONE_MOJO_CORE_PROOF.
#ifndef MOJO_BUILDFLAGS_H_
#define MOJO_BUILDFLAGS_H_

#include "build/buildflag.h"  // IWYU pragma: export

#define BUILDFLAG_INTERNAL_MOJO_USE_APPLE_CHANNEL() (0)
#define BUILDFLAG_INTERNAL_MOJO_SUPPORT_LEGACY_CORE() (1)

#endif  // MOJO_BUILDFLAGS_H_
