#ifndef STANDALONE_RENDERER_STUBS_PROTOS_PERFETTO_COMMON_BUILTIN_CLOCK_PBZERO_H_
#define STANDALONE_RENDERER_STUBS_PROTOS_PERFETTO_COMMON_BUILTIN_CLOCK_PBZERO_H_
namespace perfetto::protos::pbzero {
enum BuiltinClock {
  BUILTIN_CLOCK_UNKNOWN = 0,
  BUILTIN_CLOCK_BOOTTIME = 6,
  BUILTIN_CLOCK_MONOTONIC = 3,
};
}  // namespace perfetto::protos::pbzero
#endif
