// Standalone experimental Dawn/D3D12 render probe buildflags.
#ifndef UI_GL_BUILDFLAGS_H_
#define UI_GL_BUILDFLAGS_H_

#include "build/buildflag.h"  // IWYU pragma: export

#define BUILDFLAG_INTERNAL_DAWN_ENABLE_BACKEND_OPENGLES() (0)
#define BUILDFLAG_INTERNAL_ENABLE_SWIFTSHADER() (0)
#define BUILDFLAG_INTERNAL_USE_DAWN() (1)
#define BUILDFLAG_INTERNAL_USE_STATIC_ANGLE() (0)
#define BUILDFLAG_INTERNAL_USE_OPENGL_APITRACE() (0)
#define BUILDFLAG_INTERNAL_ENABLE_VALIDATING_COMMAND_DECODER() (0)
#define BUILDFLAG_INTERNAL_ENABLE_VULKAN() (1)
#define BUILDFLAG_INTERNAL_USE_WEBGPU_ON_VULKAN_VIA_GL_INTEROP() (0)

#endif  // UI_GL_BUILDFLAGS_H_
