#ifndef STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_DOCUMENT_ISOLATION_POLICY_MOJOM_SHARED_H_
#define STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_DOCUMENT_ISOLATION_POLICY_MOJOM_SHARED_H_

namespace network::mojom {

enum class DocumentIsolationPolicyValue {
  kNone,
  kIsolateAndRequireCorp,
  kIsolateAndCredentialless,
};

}  // namespace network::mojom

#endif  // STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_DOCUMENT_ISOLATION_POLICY_MOJOM_SHARED_H_
