#ifndef STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_INTEGRITY_ALGORITHM_MOJOM_H_
#define STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_INTEGRITY_ALGORITHM_MOJOM_H_

namespace network::mojom {

enum class IntegrityAlgorithm {
  kSha256,
  kSha384,
  kSha512,
};

}  // namespace network::mojom

#endif  // STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_INTEGRITY_ALGORITHM_MOJOM_H_
