#ifndef STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_LINK_HEADER_MOJOM_SHARED_H_
#define STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_LINK_HEADER_MOJOM_SHARED_H_

#ifndef STANDALONE_NETWORK_LINK_REL_ATTRIBUTE_DEFINED
#define STANDALONE_NETWORK_LINK_REL_ATTRIBUTE_DEFINED
namespace network::mojom {
enum class LinkRelAttribute {
  kUnspecified,
  kPreload,
  kModulePreload,
};
}  // namespace network::mojom
#endif

#endif  // STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_LINK_HEADER_MOJOM_SHARED_H_
