#ifndef STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_URL_LOADER_MOJOM_FORWARD_H_
#define STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_URL_LOADER_MOJOM_FORWARD_H_

namespace network::mojom {

class URLLoader;
class URLLoaderClient;

}  // namespace network::mojom

#endif  // STANDALONE_RENDERER_STUBS_SERVICES_NETWORK_PUBLIC_MOJOM_URL_LOADER_MOJOM_FORWARD_H_
