set(BLINK_STANDALONE_ABSEIL_SOURCES
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/casts.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/cycleclock.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/low_level_alloc.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/raw_logging.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/spinlock.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/spinlock_wait.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/strerror.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/sysinfo.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/thread_identity.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/tracing.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/internal/unscaledcycleclock.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/log_severity.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/base/throw_delegate.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/container/internal/hashtablez_sampler.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/container/internal/hashtablez_sampler_force_weak_definition.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/container/internal/raw_hash_set.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/crc/crc32c.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/crc/internal/cpu_detect.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/crc/internal/crc.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/crc/internal/crc_cord_state.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/crc/internal/crc_memcpy_fallback.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/crc/internal/crc_memcpy_x86_arm_combined.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/crc/internal/crc_non_temporal_memcpy.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/crc/internal/crc_x86_arm_combined.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/internal/address_is_readable.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/internal/decode_rust_punycode.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/internal/demangle.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/internal/demangle_rust.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/internal/examine_stack.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/internal/utf8_for_code_point.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/leak_check.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/stacktrace.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/debugging/symbolize.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/hash/internal/city.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/hash/internal/hash.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/die_if_null.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/globals.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/initialize.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/check_op.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/conditions.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/fnmatch.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/globals.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/log_format.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/log_message.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/log_sink_set.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/nullguard.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/proto.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/structured_proto.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/internal/vlog_config.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/log_entry.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/log/log_sink.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/numeric/int128.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/profiling/internal/exponential_biased.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/profiling/internal/periodic_sampler.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/profiling/internal/profile_builder.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/profiling/hashtable.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/status/internal/status_internal.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/status/status.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/status/status_payload_printer.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/status/statusor.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/ascii.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/charconv.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/cord.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/cord_analysis.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/escaping.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cord_internal.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cord_rep_btree.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cord_rep_btree_navigator.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cord_rep_btree_reader.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cord_rep_consume.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cord_rep_crc.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cordz_functions.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cordz_handle.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cordz_info.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/cordz_sample_token.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/charconv_bigint.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/charconv_parse.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/damerau_levenshtein_distance.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/escaping.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/memutil.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/ostringstream.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/pow10_helper.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/str_format/arg.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/str_format/bind.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/str_format/extension.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/str_format/float_conversion.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/str_format/output.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/str_format/parser.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/stringify_sink.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/internal/utf8.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/match.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/numbers.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/str_cat.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/str_replace.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/str_split.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/strings/substitute.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/barrier.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/blocking_counter.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/create_thread_identity.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/futex_waiter.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/kernel_timeout.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/per_thread_sem.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/pthread_waiter.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/sem_waiter.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/stdcpp_waiter.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/waiter_base.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/win32_waiter.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/mutex.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/notification.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/civil_time.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/clock.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/duration.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/format.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/civil_time_detail.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_fixed.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_format.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_if.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_impl.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_info.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_libc.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_lookup.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_name_win.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_posix.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/zone_info_source.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/time.cc
  ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/types/source_location.cc
)

if(NOT WIN32)
  list(REMOVE_ITEM BLINK_STANDALONE_ABSEIL_SOURCES
    ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/synchronization/internal/win32_waiter.cc
    ${BLINK_STANDALONE_CHROMIUM_ROOT}/third_party/abseil-cpp/absl/time/internal/cctz/src/time_zone_name_win.cc
  )
endif()
